### ISSUE TITLE
How to determine the threshold in evaluate_restrict.py and evaluate_tolerant.py

### ISSUE THREAD

**Issue by hitercs** [alan-turing-institute/SemAIDA#4]
Hi,

I found that the evaluation metrics are very sentitive to the choice of the threshold value.
I am wondering that how you determine the threshold value. 

Thanks.

**Comment by ChenJiaoyan** [comment]
Hi, 

For the metrics, you can either calculate the traditional precision/recall under a tolerant model (one annotation is scored if it's among the GT types) and a strict model (all the annotations are regarded as wrong if the concrete GT is not annotated), as described in our ColNet paper, or adopt our new hierarchical score which takes both concrete types and their ancestors into consideration (cf. our challenge http://www.cs.ox.ac.uk/isg/challenges/sem-tab/ or our resource paper https://openaccess.city.ac.uk/id/eprint/23907/).

Regarding the metric for determining a type, it varies from data to data and from model to model. A standard solution is extracting a subset of the training data to find an optimum one.

Thanks.

**Comment by hitercs** [comment]
Thanks.
