### ISSUE TITLE
ValueError in exp_T2D/predict_colnet.py

### ISSUE THREAD

**Issue by hitercs** [alan-turing-institute/SemAIDA#5]
Hi,

Thanks for your work.
When I run the [AAAI19/exp_T2D/predict_colnet.py ](https://github.com/alan-turing-institute/SemAIDA/blob/master/AAAI19/exp_T2D/predict_colnet.py)script, I run into error message:

Traceback (most recent call last):
  File "predict_colnet.py", line 122, in <module>
    p = predict(X, classifier)
  File "predict_colnet.py", line 78, in predict
    test_p = sess.run(probabilities, {input_x: test_x, dropout_keep_prob: 1.0})
ValueError: Cannot feed value of shape (930, 60, 300, 1) for Tensor u'input_x:0', which has shape '(?, 15, 300, 1)'

Could you please resolve this issue?
Thanks.

**Comment by ChenJiaoyan** [comment]
Hi, 

Maybe you can check whether the size of synthetic column is consistent in training and prediction. 

Thanks.
